name: Generate & deploy documentation

on:
    push:
        branches: [master]

jobs:
    documentation:
        runs-on: ubuntu-20.04

        # select all the node versions you want to test
        strategy:
            matrix:
                node-version: [14.x]

        steps:
            # Setup env
            - uses: actions/checkout@v2
            - uses: webfactory/ssh-agent@v0.4.1
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - name: Cache Node Modules
              id: cache-node-modules
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: node-modules-${{ hashFiles('package-lock.json') }}

            - name: Install if cache-miss
              if: steps.cache-node-modules.outputs.cache-hit != 'true'
              run: npm install

            - name: Build if cache-hit
              if: steps.cache-node-modules.outputs.cache-hit == 'true'
              run: npm run build

            - name: Build doc
              run: npm run doc

            # push to deployment repo
            - name: Push docs to one.devops
              uses: Tonacatecuhtli/github-action-push-to-another-repository@master
              with:
                  source-directory: docs
                  destination-github-repository-username: refinio
                  destination-github-repository-name: one.devops
                  destination-repository-folder: projects/one.models/latest/doc
                  user-email: devops@refinio.net
                  user-name: devops
